database:
  database: slms
  host: localhost
  password: ""
  username: slms
web_server:
  address: :443
  api_token_hash: ""
  only_https_rootlink: true
  permanent_redirect: true
  root_redirect: /manage
  session_store_key: fwnWDyyo3wzjE2vJ4HodseJAps8HVstoug0Tgqs1EsrvYbVgyE3bwnEhNSOzMcxL
  tls:
    cert_file: /var/cert/example.com.cer
    key_file: /var/cert/example.com.key
    use: true
